spring:
  application:
    name: CodePay
  datasource:
    url: ${MYSQL_CONN}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: ${JWT_SECRET}
  accessTokenExpiration: 25200000
  refreshTokenExpiration: 604800000


paystack:
    secretKey: ${PAYSTACK_SECRET_KEY}
    url: ${PAYSTACK_URL}
    verifyUrl: ${PAYSTACK_VERIFY_URL}


